CREATE TABLE IF NOT EXISTS employee_revenue_reports (
    report_id INT AUTO_INCREMENT PRIMARY KEY,
    employee_id INT NOT NULL,
    event_id INT NOT NULL,
    event_date DATE NOT NULL,
    hours_worked DECIMAL(10,2) NOT NULL DEFAULT 0,
    base_rate DECIMAL(10,2) NOT NULL DEFAULT 0,
    total_revenue DECIMAL(10,2) NOT NULL DEFAULT 0,
    employee_contribution DECIMAL(10,2) NOT NULL DEFAULT 0,
    employer_contribution DECIMAL(10,2) NOT NULL DEFAULT 0,
    social_employee DECIMAL(10,2) NOT NULL DEFAULT 0,
    social_employer DECIMAL(10,2) NOT NULL DEFAULT 0,
    gesy_employee DECIMAL(10,2) NOT NULL DEFAULT 0,
    gesy_employer DECIMAL(10,2) NOT NULL DEFAULT 0,
    cohesion_employer DECIMAL(10,2) NOT NULL DEFAULT 0,
    redundancy_employer DECIMAL(10,2) NOT NULL DEFAULT 0,
    industrial_employer DECIMAL(10,2) NOT NULL DEFAULT 0,
    net_amount DECIMAL(10,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (employee_id) REFERENCES employee(EmployeeID),
    FOREIGN KEY (event_id) REFERENCES event(EventID),
    UNIQUE KEY unique_employee_event (employee_id, event_id)
); 